// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://woomzzxjsftjzzambicq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indvb216enhqc2Z0anp6YW1iaWNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzkxNzQsImV4cCI6MjA3MTIxNTE3NH0.kvDNo1lxgnJqebRfkfPp9lX33RwjRgbddet3giOXC74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});